service: my-node-application

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
